[package]
name = "gutenberg"
version = "0.2.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
strfmt = "0.2"
gumdrop = "0.8"
bevy_reflect = {version = "0.9.1"}

serde = { version = "1.0", features = ["derive"]}
serde_yaml = "0.9"
serde_json = {version = "1.0", features = ["preserve_order"]}

[dev-dependencies]
pretty_assertions = "1.3"
