[package]
name = "gutenberg"
version = "0.2.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
strfmt = "0.2"
url = "2.3"
hex = "0.4"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
clap = { version = "4.2.7", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.3"
regex = "1.8.1"
