[package]
name = "gutenberg"
version = "0.2.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
strfmt = "0.2"
bevy_reflect = {version = "0.9.1"}
serde_json = "1.0"

serde = { version = "1.0", features = ["derive"]}
# TODO: Manually implement deserialization and serialization on addresses
# and remove this dep
toml = "0.5.10"

[dev-dependencies]
pretty_assertions = "1.3"
serde_yaml = "0.9"

