[package]
name = "gutenberg"
version = "0.2.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
url = "2.3"
hex = "0.4"
deunicode = "1.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"

# CLI dependencies
clap = { version = "4.2", features = ["derive"], optional = true }
derive_builder = {version = "0.12"}

[features]
cli = ["clap"]

[[bin]]
name = "gutenberg"
required-features = ["cli"]

[dev-dependencies]
pretty_assertions = "1.3"
regex = "1.8.1"
