[package]
name = "rust-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sui-sdk = { git = "https://github.com/MystenLabs/sui", rev = "2d985a342263ae224966e871b24beeafe11d782a" }
sui-keys = { git = "https://github.com/MystenLabs/sui", rev = "2d985a342263ae224966e871b24beeafe11d782a" }
sui-types = { git = "https://github.com/MystenLabs/sui", rev = "2d985a342263ae224966e871b24beeafe11d782a" }
sui-move-build = { git = "https://github.com/MystenLabs/sui", rev = "2d985a342263ae224966e871b24beeafe11d782a" }
sui-json-rpc-types = { git = "https://github.com/MystenLabs/sui", rev = "2d985a342263ae224966e871b24beeafe11d782a" }
sui-config = { git = "https://github.com/MystenLabs/sui", rev = "2d985a342263ae224966e871b24beeafe11d782a" }
sui-source-validation = { git = "https://github.com/MystenLabs/sui", rev = "2d985a342263ae224966e871b24beeafe11d782a" }
shared-crypto = { git = "https://github.com/MystenLabs/sui", rev = "2d985a342263ae224966e871b24beeafe11d782a" }
move-core-types = { git = "https://github.com/MystenLabs/sui", rev = "2d985a342263ae224966e871b24beeafe11d782a" }
move-package = { git = "https://github.com/MystenLabs/sui", rev = "2d985a342263ae224966e871b24beeafe11d782a" }
sui-move = { git = "https://github.com/MystenLabs/sui", rev = "2d985a342263ae224966e871b24beeafe11d782a", features = ["build"] }

bcs = "0.1"
thiserror = "1.0"
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0"
console = "0.15"
dirs = "4.0"
signature = "1.6"
dashmap = "5.0"
url = {version = "2.4", features = ["serde"]}

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
