[package]
name = "rust-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sui-sdk = { git = "https://github.com/MystenLabs/sui", branch = "devnet" }
sui-keys = { git = "https://github.com/MystenLabs/sui", branch = "devnet" }
sui-types = { git = "https://github.com/MystenLabs/sui", branch = "devnet" }
sui-json-rpc-types = { git = "https://github.com/MystenLabs/sui", branch = "devnet" }
sui-adapter = { git = "https://github.com/MystenLabs/sui", branch = "devnet" }
sui-framework-build = { git = "https://github.com/MystenLabs/sui", branch = "devnet" }
sui-framework = { git = "https://github.com/MystenLabs/sui", branch = "devnet" }
move-package = { git = "https://github.com/move-language/move", rev = "a8e95cbae69564d8928c9873b8acfabc50e642cf" }

thiserror = "1.0"
strfmt = "0.2"
gumdrop = "0.8"
bevy_reflect = {version = "0.9.1"}
dialoguer = "0.10"
tokio = {version = "1.20", features = ["macros", "rt-multi-thread"]}
clap = {version = "4.0", features = ["derive"]}
anyhow = "1.0"
console = "0.15"
hex = "0.4"
mime_guess = "2.0"
dotenv = "0.15"
glob = "0.3"
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
signature = "1.6.0"

aws-config = "0.53"
aws-sdk-s3 = "0.23"
pretty_assertions = "1.3.0"
