[package]
name = "rust-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sui-sdk = { git = "https://github.com/MystenLabs/sui", rev = "b63532e36df5b1fcccff3893509259494c719a78" }
sui-keys = { git = "https://github.com/MystenLabs/sui", rev = "b63532e36df5b1fcccff3893509259494c719a78" }
sui-types = { git = "https://github.com/MystenLabs/sui", rev = "b63532e36df5b1fcccff3893509259494c719a78" }
sui-json-rpc-types = { git = "https://github.com/MystenLabs/sui", rev = "b63532e36df5b1fcccff3893509259494c719a78" }
sui-adapter = { git = "https://github.com/MystenLabs/sui", rev = "b63532e36df5b1fcccff3893509259494c719a78" }
sui-framework-build = { git = "https://github.com/MystenLabs/sui", rev = "b63532e36df5b1fcccff3893509259494c719a78" }
sui-framework = { git = "https://github.com/MystenLabs/sui", rev = "b63532e36df5b1fcccff3893509259494c719a78" }
sui-config = { git = "https://github.com/MystenLabs/sui", rev = "b63532e36df5b1fcccff3893509259494c719a78" }
sui-source-validation = { git = "https://github.com/MystenLabs/sui", rev = "b63532e36df5b1fcccff3893509259494c719a78" }
move-package = { git = "https://github.com/move-language/move", rev = "7343821f67c070d28dcdb5bf7d2e07ced046b52f" }

thiserror = "1.0"
strfmt = "0.2"
gumdrop = "0.8"
bevy_reflect = {version = "0.9.1"}
dialoguer = "0.10"
tokio = {version = "1.20", features = ["macros", "rt-multi-thread"]}
clap = {version = "4.1.6", features = ["derive"]}
anyhow = "1.0"
console = "0.15"
hex = "0.4"
mime_guess = "2.0"
dotenv = "0.15"
glob = "0.3"
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
signature = "1.6"
colorize = "0.1"
terminal-link = "0.1"

aws-config = "0.53"
aws-sdk-s3 = "0.23"
pretty_assertions = "1.3.0"
futures = "0.3.26"
