[package]
name = "package-manager"
version = "0.2.0"
edition = "2021"

[dependencies]
gutenberg = { path = "../gutenberg" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
anyhow = "1.0"
convert_case = "0.6.0"
