[package]
name = "Gutenberg"
version = "0.14.0"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
# devnet-0.26.1
rev = "83de679c8ad35bada725b66f2eb3293d6aac4b60"

[dependencies.NftProtocol]
git = "https://github.com/Origin-Byte/nft-protocol"
# version 0.23.1
rev = "2458d4b8fe42efd232081cc0dc2a978c8c0d5fa0"

[addresses]
gutenberg = "0x0"
