[package]
name = "Gutenberg"
version = "0.14.0"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework"
# devnet-0.19.0
rev = "a8af20d94e951ecfb6d0cd47c23cf6393013d8a8"

[dependencies.Movemate]
git = "https://github.com/Origin-Byte/movemate.git"
subdir = "sui"
# devnet-0.19.0
rev = "115d56bd59cd9c0f59ac3a39b4c83872efa78608"

[dependencies.NftProtocol]
git = "https://github.com/Origin-Byte/nft-protocol"
# version 0.16.0
rev = "484ffaca16d561d8123c14138770fa99fe5591af"

[addresses]
gutenberg = "0x0"
