module gutenberg::domainall {
    /// One time witness is only instantiated in the init method
    struct DOMAINALL has drop {}

    /// Can be used for authorization of other actions post-creation. It is
    /// vital that this struct is not freely given to any contract, because it
    /// serves as an auth token.
    struct Witness has drop {}

    fun init(witness: DOMAINALL, ctx: &mut sui::tx_context::TxContext) {
        let (mint_cap, collection) = nft_protocol::collection::create(&witness, ctx);
        let delegated_witness = nft_protocol::witness::from_witness<DOMAINALL, Witness>(&Witness {});

        let creators = sui::vec_set::empty();
        sui::vec_set::insert(&mut creators, @0xd8fb1b0ed0ddd5b3d07f3147d58fdc2eb880d143);
        sui::vec_set::insert(&mut creators, @0xd8fb1b0ed0ddd5b3d07f3147d58fdc2eb880d144);

        nft_protocol::collection::add_domain(
            delegated_witness,
            &mut collection,
            nft_protocol::creators::from_creators<DOMAINALL, Witness>(
                &Witness {}, creators,
            ),
        );

        nft_protocol::display::add_collection_display_domain(
            delegated_witness,
            &mut collection,
            std::string::utf8(b"DomainAll"),
            std::string::utf8(b"Test contract generated by Gutenberg"),
        );

        nft_protocol::display::add_collection_symbol_domain(
            delegated_witness,
            &mut collection,
            std::string::utf8(b"GIUT"),
        );

        nft_protocol::display::add_collection_url_domain(
            delegated_witness,
            &mut collection,
            sui::url::new_unsafe_from_bytes(b"https://originbyte.io/"),
        );

        let tags = nft_protocol::tags::empty(ctx);
        nft_protocol::tags::add_tag(&mut tags, nft_protocol::tags::art());
        nft_protocol::tags::add_tag(&mut tags, nft_protocol::tags::profile_picture());

        nft_protocol::tags::add_collection_tag_domain(
            delegated_witness,
            &mut collection,
            tags,
        );

        sui::transfer::transfer(mint_cap, @0xd8fb1b0ed0ddd5b3d07f3147d58fdc2eb880d143);
        sui::transfer::share_object(collection);
    }

    public entry fun mint_to_address(
        name: std::string::String,
        url: vector<u8>,
        description: std::string::String,
        attribute_keys: vector<std::string::String>,
        attribute_values: vector<std::string::String>,
        mint_cap: &nft_protocol::mint_cap::MintCap<DOMAINALL>,
        receiver: address,
        ctx: &mut sui::tx_context::TxContext,
    ) {
        let nft = mint(
            name,
            url,
            description,
            attribute_keys,
            attribute_values,
            mint_cap,
            ctx,
        );

        sui::transfer::transfer(nft, receiver);
    }

    fun mint(
        name: std::string::String,
        url: vector<u8>,
        description: std::string::String,
        attribute_keys: vector<std::string::String>,
        attribute_values: vector<std::string::String>,
        mint_cap: &nft_protocol::mint_cap::MintCap<DOMAINALL>,
        ctx: &mut sui::tx_context::TxContext,
    ): nft_protocol::nft::Nft<DOMAINALL> {
        let nft = nft_protocol::nft::from_mint_cap(
            mint_cap,
            name,
            sui::url::new_unsafe_from_bytes(url),
            ctx,
        );
        let delegated_witness = nft_protocol::witness::from_witness<DOMAINALL, Witness>(&Witness {});

        nft_protocol::display::add_display_domain(
            delegated_witness, &mut nft, name, description,
        );

        nft_protocol::display::add_url_domain(
            delegated_witness, &mut nft, sui::url::new_unsafe_from_bytes(url),
        );

        nft_protocol::display::add_attributes_domain_from_vec(
            delegated_witness, &mut nft, attribute_keys, attribute_values,
        );

        nft
    }
}
