name: cargo-test
run-name: Testing Rust packages

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main, develop ]

jobs:
  test:
    name: Cargo Check + Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: check

      - uses: actions-rs/cargo@v1
        with:
          command: test

